# Generated by Django 5.1.1 on 2024-10-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObligacionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_impuesto', models.CharField(max_length=255)),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado_pago', models.BooleanField(default=False)),
                ('email_automatico', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
