# Generated by Django 5.1.1 on 2024-09-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ObligacionFiscal", "0001_initial"),
        ("Usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligacionfiscal",
            name="usuario_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Usuario.usuario"
            ),
        ),
    ]
