# Generated by Django 5.1.1 on 2024-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagoColaborador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocolaborador',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
