# Generated by Django 5.1.1 on 2024-09-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagoColaborador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocolaborador',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
