# Generated by Django 5.1.1 on 2024-09-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
