# Generated by Django 5.1.1 on 2024-09-20 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
