# Generated by Django 5.1.1 on 2024-10-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_mfa_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_secret",
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
