# Generated by Django 5.1.1 on 2024-09-20 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0002_remove_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
