# Generated by Django 5.1.1 on 2024-10-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0002_customuser_is_mfa_enabled_customuser_otp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
