# Generated by Django 5.1.1 on 2024-09-23 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0004_customuser_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="correo",
            new_name="email",
        ),
    ]
