# Generated by Django 5.1.1 on 2024-09-23 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0005_rename_correo_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="activo",
            new_name="is_active",
        ),
    ]
