# Generated by Django 5.1.1 on 2024-09-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0006_rename_activo_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(default="user", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
