# Generated by Django 5.1.1 on 2024-09-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0007_customuser_role_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="monotributo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="numero_fiscal",
            field=models.CharField(default=12345678, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Administrador", "Admin"),
                    ("Colaborador", "Colaborador"),
                    ("Usuario", "Usuario"),
                ],
                default="Usuario",
                max_length=255,
            ),
        ),
    ]
