# Generated by Django 5.1.1 on 2024-09-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0008_customuser_monotributo_customuser_numero_fiscal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
