# Generated by Django 5.1.1 on 2024-09-24 22:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0009_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
