# Generated by Django 5.1.1 on 2024-09-25 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usuario", "0010_remove_customuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="verificado",
            new_name="verified",
        ),
    ]
