# Generated by Django 5.1.1 on 2024-09-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0011_rename_verificado_customuser_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='redes_sociales',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
