# Generated by Django 5.1.1 on 2024-09-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_alter_customuser_redes_sociales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='redes_sociales',
            field=models.JSONField(default={'instagram': '@me'}),
            preserve_default=False,
        ),
    ]
